### ISSUE TITLE
Introduce Our Recent Work: SemiEvol

### ISSUE THREAD

**Issue by luo-junyu** [NOVAglow646/LLM-MLLM-paper-list#1]
Hi Qixun,

Nice work on this repository! As a fellow alumni with similar research interests, I would like to introduce our recent work, SemiEvol (https://github.com/luo-junyu/SemiEvol, https://arxiv.org/abs/2410.14745). I hope it can be included in your list.

Best regards,
Junyu

**Comment by NOVAglow646** [comment]
Hi Junyu,




Thank you for sharing your work! We will add your paper to the list as soon as possible. We appreciate your interest in and support for our repository.




Best regards,
Qixun




-----原始邮件-----
发件人:Junyu ***@***.***>
发送时间:2024-12-06 00:18:56 (星期五)
收件人: NOVAglow646/LLM-MLLM-paper-list ***@***.***>
抄送: Subscribed ***@***.***>
主题: [NOVAglow646/LLM-MLLM-paper-list] Introduce Our Recent Work: SemiEvol (Issue #1)






Hi Qixun,

As fellow alumni sharing similar research interests, I would like to introduce our recent work SemiEvol (https://github.com/luo-junyu/SemiEvol, https://arxiv.org/abs/2410.14745). I hope it could be included in your list.

Best regards,
Junyu

**Comment by luo-junyu** [comment]
Thank you, Qixun. Also, thank you for your contributions to the community.
